config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  root :to => 'feeds#feed_entries'
  get '/entries', to: 'feeds#feed_entries'
  get '/sync', to: 'feeds#sync'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :feed_entries, dependent: :destroy
  
  #for a feed to be valid lets say at minimum we should have some name and something that looks like url
  validates :name, presence: true
  validates :url, format: { with: URI.regexp, message: 'You provided invalid URL' }
end

app/models/feed_entry.rb
class FeedEntry < ApplicationRecord
    belongs_to :feed
    #validation is missing since some of the rss feeds are not very consistent in presenting similar data
    #some of them dont have published date,image or author so the only think we can validate here is url and title
    validates :title, presence: true
    validates :url, format: { with: URI.regexp, message: 'You provided invalid URL' }
    scope :newest, -> { order(published: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def feed_entries
    @entries = FeedEntry.all.newest
  end
  
  def sync
    FeedsHelper::sync

    redirect_to entries_path
  end

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    respond_to do |format|
      if @feed.save
        format.html { redirect_to feeds_path, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to feeds_path, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feed_params
      params.require(:feed).permit(:name, :url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def self.sync
    Feed.all.each do |feed|
        rss = HTTParty.get(feed.url).body
        feed_results = Feedjira.parse(rss)
        feed_results.entries.each do |entry|
          feed_entry = feed.feed_entries.where(title: entry.title).first_or_initialize

          feed_entry.update_attributes(
                        content: entry.content, author: entry.author, url: entry.url, 
                        published: entry.published, summary: entry.summary, image: entry.image)
          p "Synced Entry - #{entry.title}"
        end
        p "Synced Feed - #{feed.name}"
    end
  end
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
        <% feed.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name" %>
  </div>

  <div class="field">
    <%= form.text_field :url, placeholder: "Url" %>
  </div>

  <div class="field">
    <%= form.text_area :description, placeholder: "Description" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/feed_entries.html.erb
<p id="notice"><%= notice %></p>

<h1>All feeds</h1>
<div class="link">
  <%= link_to "Sync", :controller => :feeds, :action => :sync %>
</div>
 <% if @entries.count > 0 %>
  <table>
    <thead>
      <tr>
      <th>Image</th>
        <th>Title</th>
        <th>Published </th>
      </tr>
    </thead>

    <tbody>
      <% @entries.each do |entry| %>
        <tr>
          <td><a href="<%=entry.url %>"><%= image_tag(entry.image || 'https://www.scientificarchives.com/assets/images/no-image-200_300.png', size: "130x130") %> </a></td>
          <td><%= link_to entry.title , entry.url , target: :_blank %></td>
          <td>  <%= time_ago_in_words entry.published || Time.now %> ago </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>
<div class="link">
  <%= link_to 'New Feed', new_feed_path %>
</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= link_to feed.url , feed.url %></td>
        <td><%= feed.description %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RssReader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <div class='static-header'>
    <div class='logo-container'>
        <a href='/'>
        Simple RSS Reader
        </a>
        <div class="menu">
        <a href='/feeds'>
        Feeds
        </a>
        <a href='/entries'>
        Entries
        </a>
      </div>
    </div>
  </div>

  <div class='static-container'>
    <%= yield %>
  </div>


</html>